id: "art_gallery"
name: "現代美術館"
description: "明亮寬敞的現代美術館，目前正在舉辦新銳藝術家聯展。純白的牆面上掛著各式畫作，中央區域擺放著富有創意的雕塑作品。優希經常在假日來這裡尋找靈感。"
items:
  exhibition_guide:
    id: "exhibition_guide"
    name: "展覽指南"
    description: "詳細介紹了目前展出的作品和藝術家背景。"
    is_takeable: true
    is_useable: true
  artwork:
    id: "artwork"
    name: "藝術作品"
    description: "各種風格的現代藝術作品，從抽象到寫實都有。其中有幾幅特別吸引優希的注意。"
    is_takeable: false
    is_useable: true
  gift_shop:
    id: "gift_shop"
    name: "紀念品商店"
    description: "販售藝術相關的精美禮品，包括明信片、藝術書籍和文具。"
    is_takeable: false
    is_useable: true
connected_scenes:
  - "cafe"
  - "park"
npcs:
  - "yuki"
state:
  exhibition_theme: "新銳藝術家聯展"
  yuki_present: false
special_events:
  - id: "art_discussion"
    condition: "yuki_present == true"
    description: "優希正專注地觀賞一幅畫作，似乎陷入了沉思。"
  - id: "artist_talk"
    condition: "weekend == true and time == afternoon"
    description: "美術館正在舉辦藝術家座談會，優希看起來很感興趣。"
shop_items:
  art_book:
    id: "art_book"
    name: "藝術畫冊"
    description: "精美的現代藝術畫冊，包含了許多優秀藝術家的作品。"
    price: 1200
    gift_value: 75
  art_postcard:
    id: "art_postcard"
    name: "藝術明信片"
    description: "印有精美藝術作品的明信片，可以寫下心意送給他人。"
    price: 150
    gift_value: 35
  sketch_kit:
    id: "sketch_kit"
    name: "高級素描組"
    description: "一套專業的素描工具，包含各種規格的鉛筆和優質素描本。"
    price: 2000
    gift_value: 90