id: "cafe"
name: "溫馨咖啡廳"
description: "一間充滿藝術氣息的咖啡廳，牆上掛著許多本地藝術家的作品。空氣中瀰漫著咖啡香，背景音樂輕柔悅耳。優希正在吧台後忙碌著，不時抬頭對客人展露微笑。"
items:
  menu:
    id: "menu"
    name: "咖啡菜單"
    description: "精美的手寫菜單，除了經典咖啡，還有優希特製的季節限定飲品。"
    is_takeable: false
    is_useable: true
  sketch_book:
    id: "sketch_book"
    name: "素描本"
    description: "似乎是優希的素描本，放在吧台一角，上面畫著一些風景速寫。"
    is_takeable: false
    is_useable: true
connected_scenes:
  - "park"
  - "art_gallery"
npcs:
  - "yuki"
state:
  first_visit: true
  time_of_day: "morning"