id: "park"
name: "中央公園"
description: "一個寧靜優美的公園，有噴泉、花園和舒適的長椅。這裡是很多藝術家寫生的好去處。傍晚時分，夕陽灑在樹梢上格外動人。週末時，經常能看到優希在這裡寫生。"
items:
  bench:
    id: "bench"
    name: "長椅"
    description: "一張面向噴泉的長椅，位置絕佳，可以看到整個公園的風景。"
    is_takeable: false
    is_useable: true
  flowers:
    id: "flowers"
    name: "野花"
    description: "公園裡盛開的野花，可以摘下來送人。"
    is_takeable: true
    is_useable: true
  art_supplies:
    id: "art_supplies"
    name: "繪畫用具"
    description: "如果優希在這裡寫生，你會看到她的畫具。"
    is_takeable: false
    is_useable: true
connected_scenes:
  - "cafe"
  - "art_gallery"
npcs:
  - "yuki"
state:
  time_of_day: "evening"
  yuki_present: false
  drawing_event: false
special_events:
  - id: "sunset_drawing"
    condition: "time_of_day == evening and weekend == true"
    description: "優希正專注地畫著日落時分的公園景色。"
  - id: "chance_meeting"
    condition: "random_encounter == true"
    description: "你意外遇到正在散步的優希。"